language: nodejs
node_js:
  -stable
cache: npm

install: 
  - npm install

script:
  - npm test

deploy: 
  provider: pages
  skin-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
